//! Composing the one tirith policy file out of many.
//!
//! tirith has no policy layering of its own: its schema carries
//! `custom_rules`, `agent_rules`, `scan` and friends, but nothing like an
//! `extends`/`import`, and `TIRITH_POLICY_ROOT` points at exactly one
//! `.tirith/policy.yaml`. So a machine can natively have cerberus's rules or
//! its own or a team's, never all three.
//!
//! This module is what makes "inject custom tirith rules via cerberus" work:
//! cerberus merges its embedded base, the user's own fragments, and every
//! configured source's fragments into the single file tirith will read. That
//! composition is the risk head's counterpart to `rules::evaluate` stacking
//! source `.rhai` directories on top of the personal ones.
//!
//! Two invariants make this safe to run against remote content:
//!
//! - **A layer can tighten the posture but never loosen it.** `fail_mode`,
//!   `allow_bypass_env_noninteractive`, and `schema_version` come from the
//!   base and nowhere else; `paranoia` takes the maximum across layers.
//!   Without this a source repo could quietly turn the risk head down, which
//!   is the opposite of what adding a source is supposed to do.
//! - **A bad layer is skipped, never fatal.** The base always survives, so
//!   cerberus's own `cerberus-guard-self-tamper` keeps enforcing (and
//!   `health`'s canary keeps passing) no matter what a fragment contains.
//!
//! Output is deterministic — layers are ordered by source, then by filename,
//! never by directory-iteration order — because `init`, `source sync`, and
//! the guard-time self-heal in [`super::check_with_overlay`] all regenerate
//! this file independently and must agree on its contents.

use crate::config;
use crate::embedded;
use crate::paths::Paths;
use serde_norway::{Mapping, Value};
use std::fs;
use std::path::Path;

/// Top-level keys only cerberus's own base layer may set. A layer that
/// declares one is reporting a problem, not configuring anything: these are
/// exactly the fields that decide whether tirith fails open, whether a
/// bypass env var is honored, and which schema the file is read against.
const BASE_ONLY_KEYS: &[&str] = &[
    "schema_version",
    "fail_mode",
    "allow_bypass_env_noninteractive",
];

/// The one knob a layer may raise but not lower. Merged as a maximum rather
/// than rejected outright, so a team can ask for *more* scrutiny than
/// cerberus's default without being able to ask for less.
const PARANOIA_KEY: &str = "paranoia";

const CUSTOM_RULES_KEY: &str = "custom_rules";

const HEADER: &str = "\
# GENERATED BY cerberus — DO NOT EDIT.
#
# Composed by `cerberus init` / `cerberus source sync` from cerberus's own
# embedded base policy plus every fragment in
# ${XDG_CONFIG_HOME:-~/.config}/cerberus/tirith/ and each configured policy
# source. Edit those, then re-run `cerberus init`; anything written directly
# here is overwritten without warning (and `cerberus guard` may rewrite it
# mid-session if tirith reports it didn't load).
#
# Rules from a source are id-prefixed with that source's name.
";

/// One fragment to merge on top of the base.
pub struct Layer {
    /// How this layer is named in a problem message, e.g.
    /// `"tirith/no-curl-pipe.yaml"` or `"source 'team': cloud.yaml"`.
    pub label: String,
    /// The source name whose rule ids get prefixed with it, or `None` for
    /// the user's own fragments, which are left alone — a personal rule id
    /// is already unambiguous on the machine it lives on.
    pub namespace: Option<String>,
    pub yaml: String,
}

/// A composed policy, plus everything a caller needs to report on it.
pub struct Composed {
    pub yaml: String,
    /// Per-layer problems: a fragment that wouldn't parse, or one that tried
    /// to set a base-only key. Never fatal — see the module docs.
    pub problems: Vec<String>,
    /// How many fragments actually merged, not counting the base.
    pub layers_merged: usize,
    /// Total `custom_rules` entries in the result, base included.
    pub rule_count: usize,
}

/// Composes the overlay for `paths`: cerberus's embedded base, then the
/// user's own fragments, then each configured source's, in `config::sources`
/// order.
pub fn overlay(paths: &Paths) -> Composed {
    compose(embedded::TIRITH_POLICY, &collect_layers(paths))
}

/// Gathers every fragment on disk, in the deterministic order [`compose`]
/// merges them. Split out from [`overlay`] so `sources` can build a
/// *candidate* layer set (one that includes content it hasn't installed yet)
/// and validate it before committing to anything.
pub fn collect_layers(paths: &Paths) -> Vec<Layer> {
    let mut layers = read_fragments_from(&paths.tirith_fragments_dir(), None, "tirith");
    for source in config::sources(paths) {
        layers.extend(read_fragments_from(
            &paths.source_tirith_dir(&source.name),
            Some(source.name.clone()),
            &format!("source '{}'", source.name),
        ));
    }
    layers
}

/// Reads `*.yaml` from one directory level, sorted by filename. Not
/// recursive, matching how `rules/` works and how `sources` enforces a flat
/// `tirith/`: a nested fragment would merge invisibly or not at all, and
/// silently-dead content is the failure mode this codebase exists to avoid.
///
/// Public because `sources::check_tirith` points it at a *fetched* cache
/// directory to build a candidate layer set for validation, before any of
/// it is installed.
pub fn read_fragments_from(
    dir: &Path,
    namespace: Option<String>,
    label_prefix: &str,
) -> Vec<Layer> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<_> = entries
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_ok_and(|t| t.is_file()))
        .map(|e| e.path())
        .filter(|p| {
            matches!(
                p.extension().and_then(|x| x.to_str()),
                Some("yaml") | Some("yml")
            )
        })
        .collect();
    files.sort();

    files
        .into_iter()
        .filter_map(|path| {
            let name = path.file_name()?.to_string_lossy().into_owned();
            Some(Layer {
                label: format!("{label_prefix}: {name}"),
                namespace: namespace.clone(),
                yaml: fs::read_to_string(&path).ok()?,
            })
        })
        .collect()
}

/// The testable core: merge `layers` onto `base`. Never fails — a base that
/// won't parse (impossible for the embedded one, which is covered by
/// `shipped_tirith_overlay_validates`) falls back to emitting the base
/// verbatim, because the risk head having cerberus's own rules matters more
/// than composition succeeding.
pub fn compose(base: &str, layers: &[Layer]) -> Composed {
    let mut problems = Vec::new();

    let Some(mut acc) = serde_norway::from_str::<Value>(base)
        .ok()
        .and_then(into_mapping)
    else {
        return Composed {
            yaml: base.to_string(),
            problems: vec!["cerberus's own base tirith policy didn't parse".to_string()],
            layers_merged: 0,
            rule_count: 0,
        };
    };

    let mut layers_merged = 0;
    for layer in layers {
        match serde_norway::from_str::<Value>(&layer.yaml)
            .ok()
            .and_then(into_mapping)
        {
            Some(mut fragment) => {
                sanitize(&mut fragment, &mut acc, &layer.label, &mut problems);
                if let Some(ns) = layer.namespace.as_deref() {
                    namespace_rule_ids(&mut fragment, ns);
                }
                merge_mapping(&mut acc, fragment);
                layers_merged += 1;
            }
            None => problems.push(format!("{}: not valid YAML, skipped", layer.label)),
        }
    }

    let rule_count = acc
        .get(Value::from(CUSTOM_RULES_KEY))
        .and_then(Value::as_sequence)
        .map_or(0, Vec::len);

    let body = serde_norway::to_string(&Value::Mapping(acc))
        .unwrap_or_else(|_| embedded::TIRITH_POLICY.to_string());

    Composed {
        yaml: format!("{HEADER}\n{body}"),
        problems,
        layers_merged,
        rule_count,
    }
}

/// Every `custom_rules[]` entry that declares `examples_bad:`, as
/// `(id, examples)`. Feeds [`super::rules_that_never_fire`], which runs each
/// example through the real `tirith check` to prove the rule can actually
/// fire — see that function for why a rule that validates cleanly may still
/// never be consulted in production.
///
/// `examples_bad` is tirith's own field name for "commands this rule should
/// catch", and tirith accepts it on a custom rule (verified against 0.3.3),
/// so declaring one costs a fragment author nothing beyond the example
/// itself.
pub fn rules_with_examples(yaml: &str) -> Vec<(String, Vec<String>)> {
    let Some(mapping) = serde_norway::from_str::<Value>(yaml)
        .ok()
        .and_then(into_mapping)
    else {
        return Vec::new();
    };
    let Some(rules) = mapping
        .get(Value::from(CUSTOM_RULES_KEY))
        .and_then(Value::as_sequence)
    else {
        return Vec::new();
    };

    rules
        .iter()
        .filter_map(|rule| {
            let id = rule.get("id")?.as_str()?.to_string();
            let examples: Vec<String> = rule
                .get("examples_bad")?
                .as_sequence()?
                .iter()
                .filter_map(|e| e.as_str().map(str::to_string))
                .collect();
            (!examples.is_empty()).then_some((id, examples))
        })
        .collect()
}

fn into_mapping(value: Value) -> Option<Mapping> {
    match value {
        Value::Mapping(m) => Some(m),
        // An empty fragment parses as Null; treat it as "nothing to add"
        // rather than a problem worth reporting.
        Value::Null => Some(Mapping::new()),
        _ => None,
    }
}

/// Strips the knobs a layer isn't allowed to set, reporting each one, and
/// folds `paranoia` into `acc` as a maximum. Runs before the merge so the
/// generic [`merge_mapping`] never has to know about policy semantics.
fn sanitize(fragment: &mut Mapping, acc: &mut Mapping, label: &str, problems: &mut Vec<String>) {
    for key in BASE_ONLY_KEYS {
        if fragment.remove(Value::from(*key)).is_some() {
            problems.push(format!(
                "{label}: ignoring `{key}` — only cerberus's base policy may set it, so a \
                 layer can tighten the risk head but never loosen it"
            ));
        }
    }

    let Some(requested) = fragment
        .remove(Value::from(PARANOIA_KEY))
        .as_ref()
        .and_then(Value::as_u64)
    else {
        return;
    };
    let current = acc
        .get(Value::from(PARANOIA_KEY))
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if requested > current {
        acc.insert(Value::from(PARANOIA_KEY), Value::from(requested));
    } else if requested < current {
        problems.push(format!(
            "{label}: ignoring `paranoia: {requested}` — lower than the effective {current}, \
             and a layer may only raise it"
        ));
    }
}

/// Prefixes every `custom_rules[].id` with `ns-`, so two sources can each
/// ship a rule called `no-force-push` without colliding in the single file
/// tirith reads, and so a deny names which source produced it. Idempotent:
/// an id already carrying the prefix is left alone, which keeps re-composing
/// (init, sync, self-heal) from stacking prefixes.
fn namespace_rule_ids(fragment: &mut Mapping, ns: &str) {
    let Some(rules) = fragment
        .get_mut(Value::from(CUSTOM_RULES_KEY))
        .and_then(Value::as_sequence_mut)
    else {
        return;
    };
    let prefix = format!("{ns}-");
    for rule in rules {
        let Some(map) = rule.as_mapping_mut() else {
            continue;
        };
        let Some(id) = map.get(Value::from("id")).and_then(Value::as_str) else {
            continue;
        };
        if id.starts_with(&prefix) {
            continue;
        }
        let namespaced = format!("{prefix}{id}");
        map.insert(Value::from("id"), Value::from(namespaced));
    }
}

/// Deep-merges `fragment` into `acc`: mappings merge key by key, sequences
/// concatenate (so every layer's `custom_rules` and `agent_rules.deny`
/// accumulate rather than replacing each other — the whole point of
/// layering), and any other value from a later layer wins.
fn merge_mapping(acc: &mut Mapping, fragment: Mapping) {
    for (key, value) in fragment {
        match acc.remove(&key) {
            Some(existing) => {
                acc.insert(key, merge_value(existing, value));
            }
            None => {
                acc.insert(key, value);
            }
        }
    }
}

fn merge_value(existing: Value, incoming: Value) -> Value {
    match (existing, incoming) {
        (Value::Mapping(mut a), Value::Mapping(b)) => {
            merge_mapping(&mut a, b);
            Value::Mapping(a)
        }
        (Value::Sequence(mut a), Value::Sequence(b)) => {
            a.extend(b);
            Value::Sequence(a)
        }
        (_, incoming) => incoming,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn layer(label: &str, yaml: &str) -> Layer {
        Layer {
            label: label.to_string(),
            namespace: None,
            yaml: yaml.to_string(),
        }
    }

    fn source_layer(label: &str, ns: &str, yaml: &str) -> Layer {
        Layer {
            label: label.to_string(),
            namespace: Some(ns.to_string()),
            yaml: yaml.to_string(),
        }
    }

    fn parse(composed: &Composed) -> Mapping {
        serde_norway::from_str::<Value>(&composed.yaml)
            .map(|v| into_mapping(v).expect("composed output must be a mapping"))
            .expect("composed output must be valid YAML")
    }

    fn rule_ids(composed: &Composed) -> Vec<String> {
        parse(composed)
            .get(Value::from(CUSTOM_RULES_KEY))
            .and_then(Value::as_sequence)
            .map(|rules| {
                rules
                    .iter()
                    .filter_map(|r| r.get("id")?.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default()
    }

    /// With nothing to merge, composition must still produce the shipped
    /// policy's substance — this is what every machine with no fragments and
    /// no sources gets, which is nearly all of them.
    #[test]
    fn base_only_preserves_the_shipped_policy() {
        let composed = compose(embedded::TIRITH_POLICY, &[]);
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);
        assert_eq!(composed.layers_merged, 0);
        assert_eq!(composed.rule_count, 1);
        assert_eq!(rule_ids(&composed), vec!["cerberus-guard-self-tamper"]);

        let map = parse(&composed);
        assert_eq!(
            map.get(Value::from("fail_mode")).and_then(Value::as_str),
            Some("open")
        );
        assert_eq!(
            map.get(Value::from("paranoia")).and_then(Value::as_u64),
            Some(2)
        );
    }

    #[test]
    fn a_personal_fragment_adds_its_rules_without_renaming_them() {
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[layer(
                "tirith: mine.yaml",
                "custom_rules:\n  - id: my-rule\n    context: [exec]\n    pattern: 'foo'\n",
            )],
        );
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);
        assert_eq!(composed.layers_merged, 1);
        assert_eq!(
            rule_ids(&composed),
            vec!["cerberus-guard-self-tamper", "my-rule"]
        );
    }

    /// The reason namespacing exists: two teams both shipping the obvious
    /// rule name must both survive into the single file tirith reads.
    #[test]
    fn colliding_source_rule_ids_are_namespaced_and_both_survive() {
        let frag = "custom_rules:\n  - id: no-force-push\n    context: [exec]\n    pattern: 'a'\n";
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[
                source_layer("source 'team': a.yaml", "team", frag),
                source_layer("source 'org': a.yaml", "org", frag),
            ],
        );
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);
        assert_eq!(
            rule_ids(&composed),
            vec![
                "cerberus-guard-self-tamper",
                "team-no-force-push",
                "org-no-force-push"
            ]
        );
    }

    /// Re-composing must not stack prefixes; `init`, `sync`, and the
    /// guard-time self-heal all run this over the same content repeatedly.
    #[test]
    fn namespacing_is_idempotent() {
        let already = "custom_rules:\n  - id: team-rule\n    context: [exec]\n    pattern: 'a'\n";
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[source_layer("source 'team': a.yaml", "team", already)],
        );
        assert_eq!(
            rule_ids(&composed),
            vec!["cerberus-guard-self-tamper", "team-rule"]
        );
    }

    /// The security property that makes it safe to point cerberus at a
    /// stranger's repo: a layer cannot turn the risk head down.
    #[test]
    fn a_layer_cannot_weaken_the_posture() {
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[layer(
                "source 'hostile': evil.yaml",
                "fail_mode: closed\nallow_bypass_env_noninteractive: true\nschema_version: 99\n\
                 paranoia: 0\n",
            )],
        );

        let map = parse(&composed);
        assert_eq!(
            map.get(Value::from("fail_mode")).and_then(Value::as_str),
            Some("open"),
            "a layer must not be able to change fail_mode"
        );
        assert_eq!(
            map.get(Value::from("allow_bypass_env_noninteractive"))
                .and_then(Value::as_bool),
            Some(false),
            "a layer must not be able to open a bypass"
        );
        assert_eq!(
            map.get(Value::from("schema_version"))
                .and_then(Value::as_u64),
            Some(1)
        );
        assert_eq!(
            map.get(Value::from("paranoia")).and_then(Value::as_u64),
            Some(2),
            "paranoia must not be lowered"
        );
        assert_eq!(
            composed.problems.len(),
            4,
            "every rejected knob is reported, not silently dropped: {:?}",
            composed.problems
        );
    }

    #[test]
    fn a_layer_may_raise_paranoia() {
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[layer("tirith: strict.yaml", "paranoia: 4\n")],
        );
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);
        assert_eq!(
            parse(&composed)
                .get(Value::from("paranoia"))
                .and_then(Value::as_u64),
            Some(4)
        );
    }

    /// A broken fragment must cost only itself. If a typo in a team repo
    /// could take out cerberus's own rules, the risk head would be less
    /// trustworthy with sources than without them.
    #[test]
    fn a_malformed_fragment_is_skipped_and_the_base_survives() {
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[
                layer("tirith: broken.yaml", "this: [is not: valid: yaml"),
                layer(
                    "tirith: good.yaml",
                    "custom_rules:\n  - id: still-here\n    context: [exec]\n    pattern: 'a'\n",
                ),
            ],
        );
        assert_eq!(composed.layers_merged, 1);
        assert!(
            composed.problems.iter().any(|p| p.contains("broken.yaml")),
            "{:?}",
            composed.problems
        );
        assert_eq!(
            rule_ids(&composed),
            vec!["cerberus-guard-self-tamper", "still-here"]
        );
    }

    /// `init`, `source sync`, and the guard-time self-heal each regenerate
    /// this file independently; if they disagreed byte-for-byte the
    /// self-heal would rewrite on every single guarded call.
    #[test]
    fn composition_is_deterministic() {
        let layers = || {
            vec![
                layer(
                    "tirith: a.yaml",
                    "custom_rules:\n  - id: a\n    context: [exec]\n    pattern: 'a'\n",
                ),
                source_layer(
                    "source 'team': b.yaml",
                    "team",
                    "custom_rules:\n  - id: b\n    context: [exec]\n    pattern: 'b'\n",
                ),
            ]
        };
        let first = compose(embedded::TIRITH_POLICY, &layers());
        let second = compose(embedded::TIRITH_POLICY, &layers());
        assert_eq!(first.yaml, second.yaml);
    }

    /// Nested structure has to merge rather than replace, or a fragment
    /// adding one `agent_rules.deny` entry would wipe the sibling keys.
    #[test]
    fn nested_mappings_merge_and_sequences_concatenate() {
        let composed = compose(
            "schema_version: 1\nagent_rules:\n  deny: [one]\n  keep_me: true\n",
            &[layer(
                "tirith: more.yaml",
                "agent_rules:\n  deny: [two]\n  also: true\n",
            )],
        );
        let map = parse(&composed);
        let agent = map
            .get(Value::from("agent_rules"))
            .and_then(Value::as_mapping)
            .expect("agent_rules must survive as a mapping");
        assert_eq!(
            agent
                .get(Value::from("deny"))
                .and_then(Value::as_sequence)
                .map(Vec::len),
            Some(2),
            "sequences concatenate"
        );
        assert_eq!(
            agent.get(Value::from("keep_me")).and_then(Value::as_bool),
            Some(true),
            "an untouched sibling key must survive the merge"
        );
        assert_eq!(
            agent.get(Value::from("also")).and_then(Value::as_bool),
            Some(true)
        );
    }

    #[test]
    fn rules_with_examples_collects_only_rules_that_declare_them() {
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[layer(
                "tirith: mixed.yaml",
                "custom_rules:\n\
                 \x20 - id: has-examples\n\
                 \x20   context: [exec]\n\
                 \x20   pattern: 'a'\n\
                 \x20   examples_bad: ['do the bad thing', 'and this']\n\
                 \x20 - id: no-examples\n\
                 \x20   context: [exec]\n\
                 \x20   pattern: 'b'\n",
            )],
        );
        let found = rules_with_examples(&composed.yaml);
        assert_eq!(
            found,
            vec![(
                "has-examples".to_string(),
                vec!["do the bad thing".to_string(), "and this".to_string()]
            )],
            "a rule without examples is unverifiable, not broken, so it must not appear"
        );
    }

    #[test]
    fn rules_with_examples_is_empty_for_a_policy_that_declares_none() {
        assert!(rules_with_examples(&compose(embedded::TIRITH_POLICY, &[]).yaml).is_empty());
    }

    #[test]
    fn an_empty_fragment_is_not_a_problem() {
        let composed = compose(embedded::TIRITH_POLICY, &[layer("tirith: empty.yaml", "")]);
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);
        assert_eq!(rule_ids(&composed), vec!["cerberus-guard-self-tamper"]);
    }

    /// The composed file is what `tirith rule validate` and `tirith check`
    /// are pointed at, so it has to be a policy tirith accepts — not merely
    /// well-formed YAML.
    #[test]
    fn composed_output_validates_with_the_real_tirith() {
        if !crate::process::command_exists("tirith") {
            eprintln!("skipping: tirith not on PATH");
            return;
        }
        let composed = compose(
            embedded::TIRITH_POLICY,
            &[source_layer(
                "source 'team': a.yaml",
                "team",
                "custom_rules:\n  - id: extra\n    context: [exec]\n    pattern: 'zzz-nope'\n    \
                 severity: HIGH\n    action: block\n    title: An injected rule\n",
            )],
        );
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);

        let dir =
            std::env::temp_dir().join(format!("cerberus-compose-validate-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let file = dir.join("policy.yaml");
        fs::write(&file, &composed.yaml).unwrap();

        let status = std::process::Command::new("tirith")
            .args(["rule", "validate", "--path"])
            .arg(&file)
            .status()
            .expect("failed to run tirith rule validate");
        assert!(
            status.success(),
            "composed policy must validate; wrote {}",
            file.display()
        );
        fs::remove_dir_all(&dir).ok();
    }
}
