use super::compose;
use crate::config;
use crate::config::Paths;
use std::fs;
use std::io;
use std::path::Path;

/// Composes cerberus's tirith overlay (base + personal fragments + every
/// source's, see `heads::risk::compose`) and writes it to
/// `Paths::tirith_overlay_policy_file`, always overwriting: generated
/// content, same always-refresh contract as the rule scripts and cupcake
/// policies. Pure local file I/O — no `tirith` binary needed to write it,
/// only to enforce it later.
///
/// Every approved repo's own overlay is rewritten alongside it, since each is
/// the same composition plus that repo's `risks/` and goes stale the moment a
/// layer beneath it changes.
///
/// Returns the machine overlay's composition so callers can report how many
/// layers merged and surface any per-layer problems. Composition itself
/// never fails; a bad fragment costs only itself.
pub fn write_tirith_overlay(paths: &Paths) -> io::Result<compose::Composed> {
    let composed = compose::overlay(paths);
    write_policy(&paths.tirith_overlay_policy_file(), &composed.yaml)?;
    for repo in config::repos(paths) {
        if has_risks(paths, &repo.id) {
            let _ = write_repo_overlay(paths, &repo.id);
        }
    }
    Ok(composed)
}

/// Whether a repo's approved snapshot carries any `risks/` fragments, i.e.
/// whether it needs an overlay of its own.
pub(crate) fn has_risks(paths: &Paths, id: &str) -> bool {
    crate::sources::contains_ext_recursive(&paths.repo_risks_dir(id), "yaml")
}

/// [`write_tirith_overlay`] for one approved repo.
pub fn write_repo_overlay(paths: &Paths, id: &str) -> io::Result<compose::Composed> {
    let composed = compose::repo_overlay(paths, id);
    let file = paths
        .tirith_repo_overlay_root(id)
        .join(".tirith/policy.yaml");
    write_policy(&file, &composed.yaml)?;
    Ok(composed)
}

fn write_policy(file: &Path, yaml: &str) -> io::Result<()> {
    if let Some(parent) = file.parent() {
        fs::create_dir_all(parent)?;
    }
    // Remove whatever's there first rather than writing through it: fs::write
    // follows a symlink to its target, so a symlink into a read-only store
    // path (a broken deploy) would fail there instead of being replaced,
    // leaving the symlink itself in place. symlink_metadata sees the
    // symlink entry itself, unlike metadata, which would follow it too.
    if file.symlink_metadata().is_ok() {
        fs::remove_file(file)?;
    }
    fs::write(file, yaml)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_paths(name: &str) -> Paths {
        let root = std::env::temp_dir().join(format!(
            "cerberus-overlay-test-{}-{name}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        Paths {
            state_home: root.join("state"),
            data_home: root.join("data"),
            config_home: root.join("config"),
            cache_home: root.join("cache"),
            home: root.join("home"),
        }
    }

    /// With no fragments and no sources, the composed overlay still has to
    /// carry cerberus's own rule and its own posture — that's what nearly
    /// every machine running this gets.
    #[test]
    fn write_tirith_overlay_writes_cerberus_own_rule_when_there_is_nothing_to_merge() {
        let paths = scratch_paths("tirith-overlay");
        let composed = write_tirith_overlay(&paths).unwrap();
        assert_eq!(composed.layers_merged, 0);
        assert_eq!(composed.rule_count, 1);
        assert!(composed.problems.is_empty(), "{:?}", composed.problems);

        let written = fs::read_to_string(paths.tirith_overlay_policy_file()).unwrap();
        assert!(written.contains("cerberus-guard-self-tamper"), "{written}");
        assert!(written.contains("GENERATED BY cerberus"), "{written}");
        fs::remove_dir_all(paths.data_home.parent().unwrap()).ok();
    }

    /// The whole point of the fragments directory: a file dropped there
    /// reaches the single policy tirith reads, without a rebuild and without
    /// touching cerberus's own content.
    #[test]
    fn write_tirith_overlay_merges_a_personal_fragment() {
        let paths = scratch_paths("tirith-overlay-fragment");
        fs::create_dir_all(paths.tirith_fragments_dir()).unwrap();
        fs::write(
            paths.tirith_fragments_dir().join("mine.yaml"),
            "custom_rules:\n  - id: my-own-rule\n    context: [exec]\n    pattern: 'zzz'\n",
        )
        .unwrap();

        let composed = write_tirith_overlay(&paths).unwrap();
        assert_eq!(composed.layers_merged, 1);
        assert_eq!(composed.rule_count, 2);

        let written = fs::read_to_string(paths.tirith_overlay_policy_file()).unwrap();
        assert!(written.contains("my-own-rule"), "{written}");
        assert!(
            written.contains("cerberus-guard-self-tamper"),
            "a fragment must add to cerberus's rules, not replace them: {written}"
        );
        fs::remove_dir_all(paths.data_home.parent().unwrap()).ok();
    }

    #[test]
    fn write_tirith_overlay_is_idempotent() {
        let paths = scratch_paths("tirith-overlay-idempotent");
        write_tirith_overlay(&paths).unwrap();
        let first = fs::read_to_string(paths.tirith_overlay_policy_file()).unwrap();
        write_tirith_overlay(&paths).unwrap();
        let second = fs::read_to_string(paths.tirith_overlay_policy_file()).unwrap();
        assert_eq!(first, second);
        fs::remove_dir_all(paths.data_home.parent().unwrap()).ok();
    }
}
